// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnz3XLXSXvcUjz_RgbtXCpY4i09c7vm1Q',
    appId: '1:547003028745:web:95b4130cd66333d237afd8',
    messagingSenderId: '547003028745',
    projectId: 'ippon-app',
    authDomain: 'ippon-app.firebaseapp.com',
    storageBucket: 'ippon-app.appspot.com',
    measurementId: 'G-XMN5NXT864',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0o-TH3-kEmfM7phyw85k9s8MeHXr00xg',
    appId: '1:547003028745:android:b348534e4ec3baac37afd8',
    messagingSenderId: '547003028745',
    projectId: 'ippon-app',
    storageBucket: 'ippon-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjQh97N9tKKSQyiJYnZ-1pIvpP4PjP6_c',
    appId: '1:547003028745:ios:3be2c6bbcb9aede637afd8',
    messagingSenderId: '547003028745',
    projectId: 'ippon-app',
    storageBucket: 'ippon-app.appspot.com',
    iosBundleId: 'com.example.ippon',
  );
}
